<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxG0aBV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxG0aBV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxG0aBV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxG0aBV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTxG0aBV\App_KernelDevDebugContainer([
    'container.build_hash' => 'TxG0aBV',
    'container.build_id' => 'dfa2cd5a',
    'container.build_time' => 1640883903,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxG0aBV');
